config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "top", to: "home#top"
  get "about", to: "home#about"
  get "method", to: "home#method"
  get "store", to: "home#store"
  get "privacy", to: "home#privacy"
  get "term", to: "home#term"
  get "faq_user", to: "home#faq_user"
  get "faq_shop", to: "home#faq_shop"

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :shops, controllers: {
    sessions:      'shops/sessions',
    passwords:     'shops/passwords',
    registrations: 'shops/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'confirm_email', to: 'users/registrations#confirm_email'
  end

  namespace :admins do
    resources :shops
    resources :menus, only:[:index, :show]
    resources :users, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index]
  end
  resources :admins, only:[:index, :show, :edit, :update, :destroy]

  namespace :shops do
    resources :menus, only:[:index, :show]
    resources :orders, only:[:index, :show, :update, :destroy] do
      collection do
        get :new_orders
        get :today_orders
      end
    end
  end
  resources :shops, only:[:index, :show, :edit, :update, :destroy] do
    resources :shop_images, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :shop_tags, only:[:new, :create, :edit, :update, :destroy]
    resources :holidays, only:[:index, :new, :create, :destroy]
    resources :business_hours, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :sales, only:[:index, :show] do
      collection do
        get :month
        get :year
      end
    end
  end

  namespace :users do
    resources :shops, only:[:index, :show] do
      member do
        get :infomation
      end
      collection do
        get :search
      end
    end
  end

  resources :users, only:[:show, :edit, :update] do
    resources :orders, only:[:index, :show]
    resources :cart_items, only:[:index]
  end

  resources :menus, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :search
    end
    resources :menu_images, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :menu_tags, only:[:new, :create, :destroy]
    resources :orders, only:[:new, :create, :update, :destroy]
    resources :cart_items, only:[:create, :update]
  end

  namespace :cart_items do
    resources :orders, only:[:new, :create]
  end

  resources :orders, only:[:update]
  get "orders/fix", to: "orders#fix"
  resources :cart_items, only:[:destroy]
  resources :categories, only:[:index,:new, :create, :edit, :update, :destroy]
  resources :shop_contacts, only:[:index, :show, :new, :create] do
    collection do
      get :fix
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "no_header", only:[:about, :store]
  before_action :set_menu_ransack
  def index
    if shop_signed_in?
      redirect_to shop_path(current_shop)
    elsif admin_signed_in?
      redirect_to admins_path
    end
    menus = Menu.joins(:shop).where(shops:{is_active: true}).where(is_active: true)
    shops = Shop.where(is_active: true)
    @recommend_menus = menus.page(params[:page]).per(8)
    @popular_menus = menus.page(params[:page]).per(15)
    @popular_shops = shops.where(is_active: true).page(params[:page]).per(8)
  end

  def top
    if shop_signed_in?
      redirect_to shop_path(current_shop)
    elsif admin_signed_in?
      redirect_to admins_path
    end
    @recommend_menus = Menu.all.page(params[:page]).per(8)
    @popular_menus = Menu.all.page(params[:page]).per(15)
    @popular_shops = Shop.all.page(params[:page]).per(8)
  end

  def anout
    # ユーザー向けのLPページ
  end

  def method
    # ユーザー向けのご利用方法
  end

  def store
    # 店舗用のご利用紹介ページ
  end

  def privacy
    # ユーザー向けのプライバシーポリシーページ
  end

  def term
    # ユーザー向けの利用規約ページ
  end

  def faq_user
    # よくある質問ページ（ユーザー）
  end

  def faq_shop
    # よくある質問ページ（店舗）
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container-fluid">
  <div class="row" style="padding:0;">
    <div class="image"><%= image_tag "LP/main_lp.jpg", class: "wid-100 main-image" %></div>
  </div>
</div>

<div class="container">
  <div class="row ma-t-50">
    <div class="col-md-6 bottomin">
      <div class="lp-text_box__concept center">
        <div class="lp-text_content_top">
          <p class="left-border">CONCEPT</p>
          <h4>「おいしい」を、持ち帰ろう。</h4>
          <p class="ma-b-20">〜テイクアウトはこれからの外食の形〜</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="lp-image_box rightin">
        <div class="image1"></div>
      </div>
    </div>
  </div>
  <div class="row ma-t-30">
    <div class="col-md-12">
      <div class="text_box1 bottomin">
        <p>
          2020年を一言で表すなら、『コロナ』<br>
          コロナは、様々な分野に大きな影響を与えました。その際たる例が食生活なのではないでしょうか。<br>
          今まで通り、レストランで食事ができなくなり、自宅で食事をするということが増えました。<br>
          自分で料理をしたりコンビニで買ったりと自宅で食べる方法は様々ですが、その中の一つにテイクアウトがあります。<br>
          ”お持ち帰り = ファストフード”という概念はなくなりつつあり、普通の飲食店もテイクアウト対応のところが増えてきました。<br>
          だからこそ、もっとテイクアウトを身近に利用できるように、テイクアウトしているお店を一覧でみて、注文まで行うことができるサービスを提供いたします！
        </p>
      </div>
    </div>
  </div>

  <div class="row ma-t-50">
    <div class="col-md-5">
      <div class="lp-text_box bottomin">
        <div class="lp-text_content">
          <p class="bottom_border">PROMISE１</p>
          <h5 class="ma-b-20">テイクアウトをもっと身近に</h5>
          <p>
            テイクアウトはハンバーガーなどのファストフードしか利用したことがないという人もまだまだ多いのではないだろうか。<br>
            今や、ラーメンでもテイクアウトできる時代。「Pickup」では、どこのお店のどんなメニューがテイクアウトできるのか一目でわかるため、テイクアウトをより身近に感じることができるはずです。
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-7">
      <div class="image2 rightin"></div>
    </div>
  </div>

  <div class="row ma-t-50">
    <div class="col-md-5 order-md-2">
      <div class="lp-text_box bottomin">
        <div class="lp-text_content">
          <p class="bottom_border">PROMISE２</p>
          <h5 class="ma-b-20">注文をスマートに</h5>
          <p>
            サイトで注文したい商品を見つけたら、店舗に電話して、、、。
            そういった煩わしさは一切不要！その場でサイトから注文するだけ。
            注文メールが店舗に送信されます。<br>
            ※注文時間の店舗の状況により、提供時間が多少前後する場合がございます。
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-7 order-md-1">
      <div class="image3 leftin"></div>
    </div>
  </div>

  <div class="row ma-t-50">
    <div class="col-md-5">
      <div class="lp-text_box bottomin">
        <div class="lp-text_content">
          <p class="bottom_border">PROMISE３</p>
          <h5 class="ma-b-20">地方の飲食店を盛り上げる</h5>
          <p>
            自分の住んでいる地域の飲食店をみなさんで盛り上げていきませんか？<br>
            その地域で飲食店が盛り上がればどんどん新しいお店が増え、街全体が活気付いていきます。<br>
            まずは飲食の分野からみんなで地元を盛り上げましょう！！！
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-7">
      <div class="image4 rightin"></div>
    </div>
  </div>
</div>
<div class="container" style="padding:0">
  <div class="row">
    <div class="col-md-12">
      <div class="image fadein"><%= image_tag "LP/process.jpg", class: "wid-100" %></div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-7">
      <div class="lp-text_box bottomin">
        <div class="lp-text_content_top">
          <p class="left-border">PRODUCT</p>
          <h4>テイクアウト専用注文サイト</h4>
          <p>
            Pickupは、テイクアウトの注文専用に作られたWebアプリケーションです。<br>
            飲食店を探す目的にも使用することもできますが、「そうだ、テイクアウトしよう」と思った瞬間、効率的にテイクアウト可能な店舗を見つけ、料理を注文することができます。
          </p>
        </div>
        <div class="lp-btn_box wid-100 center ma-t-30">
          <%= link_to "Pickupを始める", new_user_registration_path, class: "lp-button-fill wid-60" %>
        </div>
      </div>
    </div>
    <div class="col-md-5">
      <div class="image5 upin"></div>
    </div>
  </div>

  <div class="row ma-t-50">
    <div class="col-md-6">
      <div class="lp-text_box bottomin">
        <div class="lp-text_content">
          <p class="bottom_border">POINT１</p>
          <h5 class="ma-b-20">テイクアウト可能なお店を探せる</h5>
          <p>
            まず食べたいものを探して、お店を決めて、テイクアウトに対応しているか確認します。
            そのような行為が一切不要になります。<br>
            当サイトに掲載しているお店は全てテイクアウト可能だからです。
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="image6 rightin"></div>
    </div>
  </div>

  <div class="row ma-t-50">
    <div class="col-md-6 order-md-2">
      <div class="lp-text_box bottomin">
        <div class="lp-text_content">
          <p class="bottom_border">POINT２</p>
          <h5 class="ma-b-20">電話での連絡が不要に</h5>
          <p>
            テイクアウトで待たずに商品を受け取るためには、事前に注文しなければなりません。<br>
            電話での注文が苦手な方や、お店の忙しい時間帯に電話するのが申し訳ないといつもためらってしまう人も安心。<br>
            Pickupは、サイトの中で注文可能なため電話で連絡する必要がありません。
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-6 order-md-1">
      <div class="image7 rightin"></div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row ma-y-50" style="padding:0;">
    <div class="image leftin"><%= image_tag "LP/soup.jpg", class: "wid-100" %></div>
  </div>
</div>

<div class="container">
  <div class="row ma-t-100">
    <div class="col-md-12">
      <div class="leftin">
        <p class="left-border">COSTMER'S VOICE</p>
        <h3>利用者の声</h3>
      </div>
    </div>
  </div>
  <div class="row ma-t-30">
    <div class="col-md-4 ma-t-30 upin">
      <h5 class="ma-b-10">注文が楽になりました</h5>
      <p>
        今まで電話で注文をしていましたが、忙しかったら申し訳ないなと思いながら連絡していました。
        そんな時にこのサイトから注文ができるので、気にしなくてよくなり大変助かっています。
      </p>
      <p class="right">
        30代　女性
      </p>
    </div>
    <div class="col-md-4 ma-t-30 upin">
      <h5 class="ma-b-10">テイクアウトできる店舗がすぐ見つかる</h5>
      <p>
        今まで、特定のお店でしかテイクアウトしていませんでした。その理由が、どこのお店がテイクアウトできるのかわからなかったからです。
        このサイトは、掲載されている商品全てがテイクアウトできるので簡単に探すことができてよく利用しています。
      </p>
      <p class="right">
        20代　男性
      </p>
    </div>
    <div class="col-md-4 ma-t-30 upin">
      <h5 class="ma-b-10">電話嫌いだから助かる</h5>
      <p>
        テイクアウトをあまりしたことがなかったのですが、その1番の理由が電話です。
        店舗に行ってから注文では待ち時間が長くなるし、電話は嫌いなのでテイクアウトをすることがなかったのですが
        このサイトを見つけてからは、よく利用しています。
      </p>
      <p class="right">
        匿名
      </p>
    </div>

  </div>

  <div class="row ma-t-50 over">
    <div class="col-md-12">
      <div class="title">
        <h2>SNS</h2>
      </div>
      <div class="center">
        <h4>準備中</h4>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid" style="padding:0;">
  <div class="row">
    <div class="col-md-12">
      <div class="fix-box right">
        <%= link_to "Pickupを始める", new_user_registration_path, class: "btn btn-success btn-sm", style: "opacity:1;" %>
      </div>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
  <script src="https://unpkg.com/scrollreveal"></script>
  <script>
    ScrollReveal().reveal('.text2', {
    duration: 1600,
    scale: 4,
    reset: false
    });

    ScrollReveal().reveal('.leftin', {
    duration: 2000,
    origin: 'left',
    distance: '50px',
    reset: false
    });

    ScrollReveal().reveal('.rightin', {
    duration: 2000,
    origin: 'right',
    distance: '50px',
    reset: false
    });

    ScrollReveal().reveal('.topin', {
    duration: 2000,
    origin: 'top',
    distance: '50px',
    reset: false
    });
    ScrollReveal().reveal('.bottomin', {
    duration: 2000,
    origin: 'bottom',
    distance: '50px',
    reset: false
    });

    ScrollReveal().reveal('.upin', {
    duration: 2000,
    scale: 0.1,
    reset: false
    });

    ScrollReveal().reveal('.fadein', {
    duration: 2000,
    reset: false
    });

  </script>

app/views/home/faq_user.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="content_box">
        <h4>よくあるご質問</h4>
        <hr>

        <div class="content_box_detail ma-b-20">
          <h6>
            <span class="question ma-r-20 red">Q.</span>
            <a data-toggle="collapse" href="#q0" role="button" aria-expanded="false" aria-controls="q0">
              「Pickup」とはどんなサイトですか<i class="fas fa-chevron-down"></i>
            </a>
          </h6>
          <div class="collapse" id="q0">
            <div class="card card-body">
              <p>
                <span class="answer ma-r-10 red">A.</span>
                「Pickup」は、テイクアウト注文専用のサイトです。<br>
                デリバリーやテイクアウトの需要が高まる中、都会ではデリバリー代行サービスが当たり前のように利用されています。
                しかし地方は、都会のように店舗や届け先が密集しているわけではないため、利用者側にも店舗様にもメリットが少ないことが挙げられます。<br>
                そこで、当サイトは地方の強みを生かしテイクアウトに特化した注文を簡単にするサイトとして「Pickup」を作りました。<br>
                また、どこのお店がテイクアウトに対応しているかを一目で確認することができるため、お店探しにも使うことができるサイトになっております。
              </p>
            </div>
          </div>
        </div>

        <div class="content_box_detail ma-b-20">
          <h6>
            <span class="question ma-r-20 red">Q.</span>
            <a data-toggle="collapse" href="#q1" role="button" aria-expanded="false" aria-controls="q1">
              登録方法がわかりません<i class="fas fa-chevron-down"></i>
            </a>
          </h6>
          <div class="collapse" id="q1">
            <div class="card card-body">
              <p>
                <span class="answer ma-r-10 red">A.</span>
                ページ下部にある利用者様向けの新規登録からお願いいたします。<br>
                メールアドレスで登録する方法と、SNSのアカウントと連携をする方法があります。<br>
                SNS連携をされた場合でも、パスワードは任意のものを設定していただきます。<br>
                また、当アプリは連絡手段にメールアドレスを利用します。如何なる場合でもメールアドレスのご本人様確認をさせていただきますので、
                お手数ですが、ご協力をお願いいたします。
              </p>
            </div>
          </div>
        </div>

        <div class="content_box_detail ma-b-20">
          <h6>
            <span class="question ma-r-20 red">Q.</span>
            <a data-toggle="collapse" href="#q2" role="button" aria-expanded="false" aria-controls="q2">
              ログイン方法がわかりません<i class="fas fa-chevron-down"></i>
            </a>
          </h6>
          <div class="collapse" id="q2">
            <div class="card card-body">
              <p>
                <span class="answer ma-r-10 red">A.</span>
                PCの場合はページ上部にある一番右のログインよりログインしてください。<br>
                スマートフォンの方も右上のメニューよりログインを選択してください。<br>
                ログインページでは、登録されているメールアドレスとパスワードを入力してログインをお願いいたします。<br>
                新規登録の際にSNSと連携して登録された場合は、該当のSNSを用いてログインする場合はパスワードの入力は不要です。（パスワードでもログインできます。）
              </p>
            </div>
          </div>
        </div>

        <div class="content_box_detail ma-b-20">
          <h6>
            <span class="question ma-r-20 red">Q.</span>
            <a data-toggle="collapse" href="#q3" role="button" aria-expanded="false" aria-controls="q3">
              どうやって注文するのですか<i class="fas fa-chevron-down"></i>
            </a>
          </h6>
          <div class="collapse" id="q3">
            <div class="card card-body">
              <p>
                <span class="answer ma-r-10 red">A.</span>
                商品をタップしていただくと「カートに追加する」または「単品注文する」を選択する画面になります。<br>
                カートに追加する場合は、他の商品も一緒に注文することができます。（まとめて注文できる商品は、同一店舗のものに限る）<br>
                メニューが決まったら注文確定画面に移ります。<br>
                受け取り時間や要望を書き込むことができるので、特別店舗に伝えたいことがある場合につきましては、そちらへ記入ください。
                なお、受け取り時間は商品の提供目安時間や定休日などによっても異なります。ご不明点がある場合は、それぞれの店舗で確認をお願いいたします。
              </p>
            </div>
          </div>
        </div>

        <div class="content_box_detail ma-b-20">
          <h6>
            <span class="question ma-r-20 red">Q.</span>
            <a data-toggle="collapse" href="#q4" role="button" aria-expanded="false" aria-controls="q4">
              決済はいつ行われますか<i class="fas fa-chevron-down"></i>
            </a>
          </h6>
          <div class="collapse" id="q4">
            <div class="card card-body">
              <p>
                <span class="answer ma-r-10 red">A.</span>
                決済の代行は当アプリではしておりません。<br>
                受け取りに行った際に店舗の決済方法に従ってください。
              </p>
            </div>
          </div>
        </div>

        <div class="content_box_detail ma-b-20">
          <h6>
            <span class="question ma-r-20 red">Q.</span>
            <a data-toggle="collapse" href="#q5" role="button" aria-expanded="false" aria-controls="q5">
              注文を送信したら確実に受け付けてくれますか<i class="fas fa-chevron-down"></i>
            </a>
          </h6>
          <div class="collapse" id="q5">
            <div class="card card-body">
              <p>
                <span class="answer ma-r-10 red">A.</span>
                希望時間の店舗の状況や不定休、注文の状況によってはキャンセルされる場合もあります。<br>
                キャンセルの場合は、キャンセル連絡が登録メールアドレスに届きます。キャンセルの理由が知りたい場合については直接店舗様へご連絡ください。
              </p>
            </div>
          </div>
        </div>

        <div class="content_box_detail ma-b-20">
          <h6>
            <span class="question ma-r-20 red">Q.</span>
            <a data-toggle="collapse" href="#q6" role="button" aria-expanded="false" aria-controls="q6">
              注文受付完了のタイミングはいつですか<i class="fas fa-chevron-down"></i>
            </a>
          </h6>
          <div class="collapse" id="q6">
            <div class="card card-body">
              <p>
                <span class="answer ma-r-10 red">A.</span>
                アプリから注文した場合、お店の営業時間であれば原則１５分以内に受付完了の連絡が来ます。営業時間外の場合は次の営業が始まってからの場合もあります。
                （店舗によっては営業時間外であっても対応していただける場合があります）<br>
                <span class="red">注：注文を送信しただけでは受付が完了したわけではありません。受付完了のメールをもって受付完了となります。</span>
              </p>
            </div>
          </div>
        </div>

        <div class="content_box_detail ma-b-20">
          <h6>
            <span class="question ma-r-20 red">Q.</span>
            <a data-toggle="collapse" href="#q7" role="button" aria-expanded="false" aria-controls="q7">
              注文のキャンセルはできますか<i class="fas fa-chevron-down"></i>
            </a>
          </h6>
          <div class="collapse" id="q7">
            <div class="card card-body">
              <p>
                <span class="answer ma-r-10 red">A.</span>
                注文送信後、店舗様が受付を確定するまでの間はユーザーメニューの注文履歴からキャンセルができます。<br>
                しかし、確定した後の場合は基本的にアプリでのキャンセルは受け付けておりません。<br>
                止むを得ずキャンセルする場合については店舗に直接ご連絡いただきますようお願いいたします。<br>
                <span class="red">注：受け取り時間によってはキャンセルできない場合もあります。</span>
              </p>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!-- メイン画像 -->
<%= render partial: "layouts/main_image" %>
<!-- / メイン画像 -->
<!-- サーチバー  -->
<%= render partial: "layouts/search_bar" %>
<!-- / サーチバー  -->

<div class="container-fluid">
  <% if @recommend_menus.present? %>
    <div class="gridWrapperTitle">
      <h6>おすすめ商品</h6>
    </div>
    <%= render partial: "menus/recommend_menus", locals:{menus: @recommend_menus} %>
  <% else %>
    <div class="non_menu center">
      <h4>登録された商品がありません</h4>
    </div>
  <% end %>
  
  <% if @popular_menus.present? %>
    <div class="gridWrapperTitle">
      <h6>人気メニュー</h6>
    </div>
    <%= render partial: "menus/menus", locals:{menus: @popular_menus} %>
    <div class="row right ma-b-20">
      <div class="col-md-12">
        <%= link_to "商品をもっと見る", menus_path, class: "arrow2" %>
      </div>
    </div>
  <% end %>

  <% if @popular_shops.present? %>
    <div class="gridWrapperTitle">
      <h6>人気レストラン</h6>
    </div>
    <%= render partial: "users/shops/shops", locals:{shops: @popular_shops} %>
    <div class="row right ma-b-20">
      <div class="col-md-12">
        <%= link_to "お店をもっと見る", users_shops_path, class: "arrow2" %>
      </div>
    </div>
  <% end %>

</div>

app/views/home/method.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="content_box">
        <h4>ご購入方法</h4>
        <hr>

        <div class="content_box_title ma-y-30">
          <h4 class="center">\"簡単３ステップで注文が可能"/</h4>
        </div>
        <div class="content_box_image ma-b-30">
          <%= image_tag "method/step1.jpg", class:"wid-100" %>
          <%= image_tag "method/step2-1.jpg", class:"wid-100" %>
          <%= image_tag "method/step3-1.jpg", class:"wid-100" %>
        </div>
        <div class="content_box_detail ma-b-30">
          <ul class="font-10">
            <li>
              ご注文の受け取り時間の指定は、店舗の<span class="red">営業時間内</span>でお願いいたします。営業時間外に受け取り指定した注文はできかねます。<br>
              なお、商品ごとにその店舗が提供までの目安時間も設定されており、現在が営業時間内であっても商品によっては注文することができませんのでご了承ください。
            </li>
            <li>
              <span class="red">受け取りの時間が多少前後する場合もございます。</span><br>
              店舗様には、商品ごとに提供目安時間を設定していただいております。しかし、それでも店舗状況によって前後することがございますのでご了承ください。
            </li>
            <li>
              一度送信した注文は、サイト上でキャンセルできなくなっております。止むを得ずキャンセルしなければならない場合については店舗様に直接ご連絡ください。
            </li>
            <li>
              ご注文の無断キャンセルは、規約違反となります。アカウントの停止をさせていただく場合もございますので、ご注意ください。<br>
              また、注文に発生した料金についてはご負担いただきます。詳しくは利用規約をご覧ください。
            </li>
          </ul>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="content_box">
        <h4>事業者用ページtop</h4>
        <hr>

        <div class="content_box_title ma-t-30">
          <h6 class="center">準備中</h6>
        </div>
        <div class="content_box_detail">
          <%= link_to "店舗管理者としてログインする", new_shop_session_path %>
        </div>

      </div>
    </div>
  </div>
</div>