config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "top", to: "home#top"
  get "about", to: "home#about"
  get "method", to: "home#method"
  get "store", to: "home#store"
  get "privacy", to: "home#privacy"
  get "term", to: "home#term"
  get "faq_user", to: "home#faq_user"
  get "faq_shop", to: "home#faq_shop"

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :shops, controllers: {
    sessions:      'shops/sessions',
    passwords:     'shops/passwords',
    registrations: 'shops/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'confirm_email', to: 'users/registrations#confirm_email'
  end

  namespace :admins do
    resources :shops
    resources :menus, only:[:index, :show]
    resources :users, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index]
  end
  resources :admins, only:[:index, :show, :edit, :update, :destroy]

  namespace :shops do
    resources :menus, only:[:index, :show]
    resources :orders, only:[:index, :show, :update, :destroy] do
      collection do
        get :new_orders
        get :today_orders
      end
    end
  end
  resources :shops, only:[:index, :show, :edit, :update, :destroy] do
    resources :shop_images, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :shop_tags, only:[:new, :create, :edit, :update, :destroy]
    resources :holidays, only:[:index, :new, :create, :destroy]
    resources :business_hours, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :sales, only:[:index, :show] do
      collection do
        get :month
        get :year
      end
    end
  end

  namespace :users do
    resources :shops, only:[:index, :show] do
      member do
        get :infomation
      end
      collection do
        get :search
      end
    end
  end

  resources :users, only:[:show, :edit, :update] do
    resources :orders, only:[:index, :show]
    resources :cart_items, only:[:index]
  end

  resources :menus, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :search
    end
    resources :menu_images, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :menu_tags, only:[:new, :create, :destroy]
    resources :orders, only:[:new, :create, :update, :destroy]
    resources :cart_items, only:[:create, :update]
  end

  namespace :cart_items do
    resources :orders, only:[:new, :create]
  end

  resources :orders, only:[:update]
  get "orders/fix", to: "orders#fix"
  resources :cart_items, only:[:destroy]
  resources :categories, only:[:index,:new, :create, :edit, :update, :destroy]
  resources :shop_contacts, only:[:index, :show, :new, :create] do
    collection do
      get :fix
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :phone_number, presence: true

  has_many :orders

  has_many :cart_items

  # omniauthのコールバック時に呼ばれるメソッド
  # def self.from_omniauth(auth)
  #   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #     uid:      auth.uid,
  #     provider: auth.provider,
  #     user.email = auth.info.email
  #     user.password = Devise.friendly_token[0,20]
  #   end
  # end

  # facebook用
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.new(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end

  # フルネームで表示する
  def full_name
    self.last_name + " " + self.first_name
  end

  # カナのフルネームを表示
  def kana_full_name
    self.kana_last_name + " " + self.kana_first_name
  end

  # 該当の商品がすでにカートに入っているかを判別
  def cart_already_include(menu)
    cart_items = self.cart_items
    if cart_items.count != 0
      cart_items.each do |item|
        if item.menu_id == menu.id
          return true
        else
          next
        end
      end
      return false
    else
      return false
    end
  end

  # カートに入っている商品の中で一番完成予定が長いものを出力
  def max_estimated_time
    result = 0
    self.cart_items.each do |item|
      if item.menu.estimated_time > result
        result = item.menu.estimated_time
      end
    end
    return result
  end

  # カートに入っている商品の合計金額を算出
  def cart_items_total_price
    result = 0
    self.cart_items.each do |item|
      result += item.menu.price * item.amount
    end
    return result
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  layout "shop_app"
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @orders = @user.orders
  end

  def edit
  end

  def update

  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :phone_number, :email)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # callback for facebook
  def facebook
    callback_for(:facebook)
  end

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.find_for_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url(data: session["devise.#{provider}_data"])
    end
  end

  def failure
    redirect_to root_path
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def confirm_email
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :kana_last_name, :kana_first_name, :phone_number, :uid, :provider])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   root_path
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    confirm_email_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/users/shops_controller.rb
class Users::ShopsController < ApplicationController
  before_action :set_shop_ransack
  def index
    @shops = Shop.where(is_active: true).page(params[:page]).per(20)
  end

  def search
    @search_shop = Shop.ransack(params[:q]) 
    @search_shops = @search_shop.result.where(is_active: true)
    @shops = @search_shops.page(params[:page]).per(20)
  end

  def show
    @shop = Shop.find(params[:id])
    unless @shop.is_active?
      redirect_to root_path
    end
    @menus = @shop.menus.where(is_active: true)
    @popular_menus = @menus.shuffle.first(4)
    @food_menus = @menus.where(menu_type: "フード")
    @drink_menus = @menus.where(menu_type: "ドリンク")
    @dessert_menus = @menus.where(menu_type: "デザート")
  end

  def infomation
    @shop = Shop.find(params[:id])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :admin_or_user!
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user == current_user
      if @user.update(user_params)
        flash[:success] = "変更を保存しました"
        redirect_to user_path(@user)
      else
        flash[:danger] = "変更できませんでした"
        render "edit"
      end
    else
      flash[:danger] = "他人の情報は変更できません"
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :phone_number, :email)
  end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/shops_helper.rb
module Users::ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/edit.html.erb
<h1>Admins::Users#edit</h1>
<p>Find me in app/views/admins/users/edit.html.erb</p>

app/views/admins/users/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="content_box">
        <h5>ユーザー一覧</h5>
        <div class="content_box_detail">
          <table class="table table-hover table-striped">
            <thead>
              <tr>
                <th>ID</th>
                <th>氏名</th>
                <th>電話番号</th>
                <th>メールアドレス</th>
                <th>利用回数</th>
              </tr>
            </thead>
            <tbody>
              <% if @users.present? %>
                <% @users.each do |user| %>
                  <tr class="pointer" data-href="<%= admins_user_path(user) %>">
                    <td><%= user.id %></td>
                    <td><%= user.full_name %></td>
                    <td><%= user.phone_number %></td>
                    <td><%= user.email %></td>
                    <td><%= user.orders.count %>回</td>
                  </tr>
                <% end %>
              <% else %>
                <tr>
                  <td>
                    登録ユーザーがいません
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="row center ma-b-20">
    <div class="col-md-12">
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admins/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="content_box">
        <div class="user_name-box">
          <span class="font-20">氏名：<%= @user.full_name %></span>
        </div>
        <div class="user_info-box">
          <div class="phone_number_box">
            <p>電話番号：<%= @user.phone_number %></p>
          </div>
          <div class="email_box">
            <p>Eメール：<%= @user.email %></p>
          </div>
        </div>
        <div class="edit_btn right">
          <%= link_to "編集", edit_admins_user_path(@user), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="content_box">
        <h5>注文履歴一覧</h5>
        <div class="content_box_detail">
          <table class="table table-hover table-striped">
            <thead>
              <tr>
                <th>注文店舗</th>
                <th>受取日時</th>
                <th>金額</th>
              </tr>
            </thead>
            <tbody>
              <% if @orders.present? %>
                <% @orders.each do |order| %>
                  <tr class="pointer" data-href="<%= shops_order_path(order) %>">
                    <td><%= order.shop.name %></td>
                    <td><%= order.takeaway_datetime.strftime("%Y年%m月%d日 %H:%M") %></td>
                    <td>¥<%= price(order.total_payment) %></td>
                  </tr>
                <% end %>
              <% else %>
                <tr>
                  <td colspan=3>
                    まだ注文がありません
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
jQuery(function ($) {
  //data-hrefの属性を持つtrを選択しclassにclickableを付加
  $("tr[data-href]")
    .addClass("clickable")

  //クリックイベント
  .click(function (e) {
    //e.targetはクリックした要素自体、それがa要素以外であれば
    if (!$(e.target).is("a")) {
      //その要素の先祖要素で一番近いtrの
      //data-href属性の値に書かれているURLに遷移する
      window.location = $(e.target).closest("tr").data("href");
    }
  });
});
</script>