config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "top", to: "home#top"
  get "about", to: "home#about"
  get "method", to: "home#method"
  get "store", to: "home#store"
  get "privacy", to: "home#privacy"
  get "term", to: "home#term"
  get "faq_user", to: "home#faq_user"
  get "faq_shop", to: "home#faq_shop"

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :shops, controllers: {
    sessions:      'shops/sessions',
    passwords:     'shops/passwords',
    registrations: 'shops/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'confirm_email', to: 'users/registrations#confirm_email'
  end

  namespace :admins do
    resources :shops
    resources :menus, only:[:index, :show]
    resources :users, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index]
  end
  resources :admins, only:[:index, :show, :edit, :update, :destroy]

  namespace :shops do
    resources :menus, only:[:index, :show]
    resources :orders, only:[:index, :show, :update, :destroy] do
      collection do
        get :new_orders
        get :today_orders
      end
    end
  end
  resources :shops, only:[:index, :show, :edit, :update, :destroy] do
    resources :shop_images, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :shop_tags, only:[:new, :create, :edit, :update, :destroy]
    resources :holidays, only:[:index, :new, :create, :destroy]
    resources :business_hours, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :sales, only:[:index, :show] do
      collection do
        get :month
        get :year
      end
    end
  end

  namespace :users do
    resources :shops, only:[:index, :show] do
      member do
        get :infomation
      end
      collection do
        get :search
      end
    end
  end

  resources :users, only:[:show, :edit, :update] do
    resources :orders, only:[:index, :show]
    resources :cart_items, only:[:index]
  end

  resources :menus, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :search
    end
    resources :menu_images, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :menu_tags, only:[:new, :create, :destroy]
    resources :orders, only:[:new, :create, :update, :destroy]
    resources :cart_items, only:[:create, :update]
  end

  namespace :cart_items do
    resources :orders, only:[:new, :create]
  end

  resources :orders, only:[:update]
  get "orders/fix", to: "orders#fix"
  resources :cart_items, only:[:destroy]
  resources :categories, only:[:index,:new, :create, :edit, :update, :destroy]
  resources :shop_contacts, only:[:index, :show, :new, :create] do
    collection do
      get :fix
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :menu
end

app/controllers/cart_items/orders_controller.rb
class CartItems::OrdersController < ApplicationController
  def new
    @order = Order.new
    @order_item = OrderItem.new
    @cart_items = current_user.cart_items
    unless @cart_items.present?
      redirect_to root_path
    end
    @shop = @cart_items[0].menu.shop
  end

  def create
    @shop = current_user.cart_items[0].menu.shop
    @cart_items = current_user.cart_items
    @order = current_user.orders.build(order_params)
    @order.shop_id = @shop.id
    if @order.is_holiday_order?
      @amount = params[:order][:amount]
      flash.now[:danger] = "受け取り希望日は定休日です"
      render :new
    else
      if @order.is_now_after?
        if @order.is_business_hour_order?
          if @order.is_between_lastOrder_to_close?
            flash.now[:danger] = "注文できませんでした。ラストオーダーを過ぎています"
            render :new
          else
            if @order.save
              @cart_items.each do |cart_item|
                OrderItem.create(
                  order_id: @order.id,
                  menu_id: cart_item.menu.id,
                  menu_name: cart_item.menu.name,
                  menu_price: cart_item.menu.price,
                  menu_fee: cart_item.menu.fee,
                  menu_amount: cart_item.amount
                )
              end
              if @order.is_after_long_serve_time?
                @cart_items.destroy_all
                OrderMailer.send_user_order(@order).deliver_later
                redirect_to orders_fix_path
              else
                @order.destroy 
                flash.now[:danger] = "注文できませんでした。受け取り時間を商品の提供目安より後に設定してください"
                render :new
              end
            else
              flash[:danger] = "注文できませんでした。入力内容を確認してください"
              render :new
            end
          end
        else
          flash.now[:danger] = "注文できませんでした。受け取り日時が営業時間外になっています"
          render :new
        end
      else
        flash.now[:danger] = "注文できませんでした。受け取り日時が過去になっています"
        render :new
      end
    end
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :shop_id, :reserve_number, :takeaway_datetime, :requested, :status)
  end
  def order_item_params
    params.require(:order_item).permit(:order_id, :menu_id, :menu_name, :menu_price, :menu_amount)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :admin_or_user!
  def index
    @cart_items = CartItem.where(user_id: current_user.id)
  end

  def create
    @menu = Menu.find(params[:menu_id])
    if current_user.cart_items.blank?
      if current_user.cart_already_include(@menu)
        @cart_item = CartItem.find_by(menu_id: @menu.id, user_id: current_user.id)
        @cart_item.update(
          amount: @cart_item.amount + params[:cart_item][:amount].to_i
        )
        flash[:success] = "カートに追加しました"
        redirect_to user_cart_items_path(current_user)
      else
        @cart_item = current_user.cart_items.build(cart_item_params)
        if @cart_item.save
          flash[:success] = "カートに追加しました"
          redirect_to user_cart_items_path(current_user)
        else
          flash[:danger] = "追加にできませんでした"
          redirect_to menus_path
        end
      end
    elsif current_user.cart_items.present? && current_user.cart_items[0].menu.shop == @menu.shop
      if current_user.cart_already_include(@menu)
        @cart_item = CartItem.find_by(menu_id: @menu.id, user_id: current_user.id)
        @cart_item.update(
          amount: @cart_item.amount + params[:cart_item][:amount].to_i
        )
        flash[:success] = "カートに追加しました"
        redirect_to user_cart_items_path(current_user)
      else
        @cart_item = current_user.cart_items.build(cart_item_params)
        if @cart_item.save
          flash[:success] = "カートに追加しました"
          redirect_to user_cart_items_path(current_user)
        else
          flash[:danger] = "追加にできませんでした"
          redirect_to menus_path
        end
      end
    else
      flash[:danger] = "すでにカートの中に他店舗の商品があるため追加できません"
      redirect_to user_cart_items_path(current_user)
    end

  end

  def update
    if user_signed_in?
      @cart_item = CartItem.find(params[:id])
      if params[:amount] == "minus"
        @cart_item.amount = @cart_item.amount - 1
      elsif params[:amount] == "plus"
        @cart_item.amount = @cart_item.amount + 1
      end

      if @cart_item.save
        redirect_to user_cart_items_path(current_user)
      else
        flash[:danger] = "変更できませんでした"
        redirect_to user_cart_items_path(current_user)
      end
    else
      flash[:danger] = "カートの商品を変更するにはログインが必要です"
      redirect_to new_user_session_path
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:success] = "削除しました"
    redirect_to user_cart_items_path(current_user)
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:user_id, :menu_id, :amount)
  end

end

app/helpers/cart_items/orders_helper.rb
module CartItems::OrdersHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="content_box">
        <h4 class="center">まとめて注文</h4>
        <div class="back_btn">
          <i class="fas fa-angle-left fa-lg"></i><%= link_to "戻る", 'javascript:history.back()', class: "font-20" %>
        </div>
        <hr>
        <% if @cart_items.present? %>
          <% @cart_items.each do |cart_item| %>
            <div class="row">
              <div class="col-7">
                <p class="m-text"><%= link_to cart_item.menu.shop.name, users_shop_path(cart_item.menu.shop), class:"gray" %></p>
                <h5><%= cart_item.menu.name %></h5>
                <h6>¥<%= price(cart_item.menu.price) %></h6>
                <div class="amount_counter ma-t-10">
                  <% if cart_item.amount == 1 %>
                    <span id="minusButton" class="pointer minusBtn"><a href="<%= cart_item_path(cart_item) %>" data-method="delete"><i class="fas fa-minus-circle minusBtn"></i></a></span>
                  <% else %>
                    <span id="minusButton" class="pointer minusBtn"><a href="<%= menu_cart_item_path(cart_item.menu, cart_item, amount:"minus") %>" data-method="patch"><i class="fas fa-minus-circle minusBtn"></i></a></span>
                  <% end %>
                  <span class="ma-x-20"><%= cart_item.amount %></span>
                  <span id="plusButton" class="pointer plusBtn"><a href="<%= menu_cart_item_path(cart_item.menu, cart_item, amount:"plus") %>" data-method="patch"><i class="fas fa-plus-circle plusBtn"></i></a></span>
                </div>
              </div>
              <div class="col-5 center">
                <% if cart_item.menu.menu_images.present? %>
                  <%= image_tag cart_item.menu.main_image.file_name.thumb_square.to_s, class: "wid-70" %>
                <% else %>
                  <%= image_tag "noimage.png", class: "wid-70" %>
                <% end %>
              </div>
            </div>
            <hr>
          <% end %>
        <% else %>
          <h5 class="center" style="height:100px">カートに商品は入っていません。</h5>
        <% end %>
        <div class="field">
          <h5>お会計金額:<span class="ma-l-30">¥</span><span id="menu_price"><%= price(current_user.cart_items_total_price) %></span></h5>
        </div>

        <% if @cart_items.present? %>
          <div class="field">
            <h5>完成予定時間</h5>
            <h6><%= current_user.max_estimated_time %><span class="ma-x-10">〜</span><%= current_user.max_estimated_time + 10 %>分</h6>
          </div>
        <% end %>

        <div class="actions center">
          <% if @cart_items.present? %>
            <%= link_to "買い物を続ける", users_shop_path(@cart_items[0].menu.shop), class: "button-fill" %>
            <%= link_to "注文に進む", new_cart_items_order_path, class: "button-fill" %>
          <% else %>
            <%= link_to "買い物を続ける", root_path, class: "button-fill" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>