config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "top", to: "home#top"
  get "about", to: "home#about"
  get "method", to: "home#method"
  get "store", to: "home#store"
  get "privacy", to: "home#privacy"
  get "term", to: "home#term"
  get "faq_user", to: "home#faq_user"
  get "faq_shop", to: "home#faq_shop"

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :shops, controllers: {
    sessions:      'shops/sessions',
    passwords:     'shops/passwords',
    registrations: 'shops/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'confirm_email', to: 'users/registrations#confirm_email'
  end

  namespace :admins do
    resources :shops
    resources :menus, only:[:index, :show]
    resources :users, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index]
  end
  resources :admins, only:[:index, :show, :edit, :update, :destroy]

  namespace :shops do
    resources :menus, only:[:index, :show]
    resources :orders, only:[:index, :show, :update, :destroy] do
      collection do
        get :new_orders
        get :today_orders
      end
    end
  end
  resources :shops, only:[:index, :show, :edit, :update, :destroy] do
    resources :shop_images, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :shop_tags, only:[:new, :create, :edit, :update, :destroy]
    resources :holidays, only:[:index, :new, :create, :destroy]
    resources :business_hours, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :sales, only:[:index, :show] do
      collection do
        get :month
        get :year
      end
    end
  end

  namespace :users do
    resources :shops, only:[:index, :show] do
      member do
        get :infomation
      end
      collection do
        get :search
      end
    end
  end

  resources :users, only:[:show, :edit, :update] do
    resources :orders, only:[:index, :show]
    resources :cart_items, only:[:index]
  end

  resources :menus, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :search
    end
    resources :menu_images, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :menu_tags, only:[:new, :create, :destroy]
    resources :orders, only:[:new, :create, :update, :destroy]
    resources :cart_items, only:[:create, :update]
  end

  namespace :cart_items do
    resources :orders, only:[:new, :create]
  end

  resources :orders, only:[:update]
  get "orders/fix", to: "orders#fix"
  resources :cart_items, only:[:destroy]
  resources :categories, only:[:index,:new, :create, :edit, :update, :destroy]
  resources :shop_contacts, only:[:index, :show, :new, :create] do
    collection do
      get :fix
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/menu_image.rb
class MenuImage < ApplicationRecord
  belongs_to :menu

  mount_uploader :file_name, MenusUploader

  validates :file_name, presence: true
end

app/controllers/menu_images_controller.rb
class MenuImagesController < ApplicationController
  layout "shop_app"
  before_action :admin_or_shop!
  before_action :set_menu

  def index
    @menu_images = @menu.menu_images.order(is_main: "desc")
    @main_image = @menu_images.find_by(is_main: true)
  end

  def new
    @menu_image = MenuImage.new
  end

  def create
    if admin_signed_in?
      if @menu.menu_images.count < 4
        if params[:menu_image][:is_main].present?
          if @menu.menu_images.present?
            @menu.menu_images.each do |image|
              if image.is_main?
                image.update(is_main: false)
              end
            end
            @menu_image = @menu.menu_images.build(menu_image_params)
            if @menu_image.save
              flash[:success] = "商品のメイン画像を追加しました"
              redirect_to menu_menu_images_path(@menu)
            else
              flash[:danger] = "画像を追加できませんでした。ファイルを選択してください"
              render :new
            end
          else
            @menu_image = @menu.menu_images.build(menu_image_params)
            if @menu_image.save
              flash[:success] = "商品のメイン画像を追加しました"
              redirect_to menu_menu_images_path(@menu)
            else
              flash[:danger] = "画像を追加できませんでした。ファイルを選択してください"
              render :new
            end
          end
        else
          if @menu.menu_images.present?
            @menu_image = @menu.menu_images.build(menu_image_params)
            if @menu_image.save
              flash[:success] = "商品の画像を追加しました"
              redirect_to menu_menu_images_path(@menu)
            else
              flash[:danger] = "画像を追加できませんでした。ファイルを選択してください"
              render :new
            end
          else
            @menu_image = @menu.menu_images.build(menu_image_params)
            @menu_image.is_main = true
            if @menu_image.save
              flash[:success] = "商品のメイン画像を追加しました"
              redirect_to menu_menu_images_path(@menu)
            else
              flash[:danger] = "画像を追加できませんでした。ファイルを選択してください"
              render :new
            end
          end
        end
      else
        flash[:danger] = "商品の画像は４枚までしか追加できません"
        redirect_to menu_menu_images_path(@menu)
      end
    elsif shop_signed_in?
      if @menu.menu_images.count < 4
        if @menu.shop == current_shop
          if params[:menu_image].present?
            if params[:menu_image][:is_main] == "true"
              if @menu.menu_images.present?
                @menu.menu_images.each do |image|
                  if image.is_main?
                    image.update(is_main: false)
                  end
                end
                @menu_image = @menu.menu_images.build(menu_image_params)
                if @menu_image.save
                  flash[:success] = "商品のメイン画像を追加しました"
                  redirect_to menu_menu_images_path(@menu)
                else
                  flash[:danger] = "画像を追加できませんでした。ファイルを選択してください"
                  render :new
                end
              else
                @menu_image = @menu.menu_images.build(menu_image_params)
                if @menu_image.save
                  flash[:success] = "商品のメイン画像を追加しました"
                  redirect_to menu_menu_images_path(@menu)
                else
                  flash[:danger] = "画像を追加できませんでした。ファイルを選択してください"
                  render :new
                end
              end
            else
              if @menu.menu_images.present?
                @menu_image = @menu.menu_images.build(menu_image_params)
                if @menu_image.save
                  flash[:success] = "商品の画像を追加しました"
                  redirect_to menu_menu_images_path(@menu)
                else
                  flash[:danger] = "画像を追加できませんでした。"
                  render :new
                end
              else
                @menu_image = @menu.menu_images.build(menu_image_params)
                @menu_image.is_main = true
                if @menu_image.save
                  flash[:success] = "商品のメイン画像を追加しました"
                  redirect_to menu_menu_images_path(@menu)
                else
                  flash[:danger] = "画像を追加できませんでした。ファイルを選択してください"
                  render :new
                end
              end
            end
          else
            @menu_image = MenuImage.new
            flash.now[:danger] = "画像を選択してください"
            render :new
          end
        else
          @menu_image = MenuImage.new
          flash[:danger] = "他店が出品した商品の画像は追加できません"
          redirect_to root_path
        end
      else
        @menu_image = MenuImage.new
        flash[:danger] = "商品の画像は４枚までしか追加できません"
        redirect_to menu_menu_images_path(@menu)
      end
    end
  end

  def edit
    @menu_image = @menu.menu_images.find(params[:id])
  end

  def update
    @menu_image = @menu.menu_images.find(params[:id])
    if admin_signed_in?
      if params[:menu_image].nil?
        flash.now[:danger] = "商品の画像を選択してください"
        render :edit
      else
        if @menu_image.update(menu_image_params)
          flash[:success] = "変更を保存しました"
          redirect_to menu_menu_images_path(@menu)
        else
          flash[:danger] = "変更できませんでした"
          render :edit
        end
      end
    elsif shop_signed_in?
      if @menu.shop == current_shop
        if params[:menu_image].present?
          if params[:menu_image][:is_main] == "true"
            @main_image = @menu.menu_images.find_by(is_main: true)
            if @menu_image.update(menu_image_params)
              @main_image.update(is_main: false)
              flash[:success] = "変更を保存しました"
              redirect_to menu_menu_images_path(@menu)
            else
              flash[:danger] = "変更できませんでした"
              render :edit
            end
          else
            if @menu_image.update(menu_image_params)
              flash[:success] = "変更を保存しました"
              redirect_to menu_menu_images_path(@menu)
            else
              flash[:danger] = "変更できませんでした"
              render :edit
            end
          end
        else
          flash.now[:danger] = "画像を選択してください"
          render :edit
        end
      else
        flash[:danger] = "多店舗の商品画像は変更できません"
        redirect_to root_path
      end
    end  
  end

  def destroy
    if @menu.shop == current_shop
      @menu_image = @menu.menu_images.find(params[:id])
      if @menu_image.is_main?
        flash[:danger] = "メイン画像は削除できません"
        redirect_to menu_menu_images_path(@menu)
      else
        if @menu_image.destroy
          flash[:success] = "画像を削除しました"
          redirect_to menu_menu_images_path(@menu)
        else
          flash[:danger] = "削除できませんでした"
          redirect_to menu_menu_images_path(@menu)
        end
      end
    else
      flash[:danger] = "多店舗のメニューは削除できません"
      redirect_to root_path
    end
  end

  private

  def menu_image_params
    params.require(:menu_image).permit(:menu_id, :file_name, :is_main)
  end

  def set_menu
    @menu = Menu.find(params[:menu_id])
  end

end

app/helpers/menu_images_helper.rb
module MenuImagesHelper
end

app/views/menu_images/_form.html.erb
<div class="field">
  <%= image_tag img, class: "wid-100", id: "img_prev" %>
  <%= f.file_field :file_name, class: "font-10", id: "input_img" %>
</div>

<% unless @menu_image.is_main? %>
  <div class="field">
    <%= f.check_box :is_main, {class: "check_box"}, true, false %>
    <%= f.label :is_main, "この画像をメインにする" %>
  </div>
<% end %>

<div class="actions center">
  <%= f.submit btn, class: "button-fill", id:"load_btn" %>
</div>
<div id="overlay">
  <div class="spinner-border text-light" role="status" id="load_spinner">
    <span class="sr-only">Loading...</span>
  </div>
</div>
<script>
jQuery(function ($) {
  $("#load_btn").click(function(){
    $("#overlay").fadeIn(500);
    console.log("画像を保存しています");
  });
});
$(function () {
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $("#img_prev").attr("src", e.target.result);
      };
      reader.readAsDataURL(input.files[0]);
    }
  }
  $("#input_img").change(function () {
    readURL(this);
  });
});
</script>

app/views/menu_images/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="form_box">
        <h4 class="center">『<%= @menu.name %>』<br>画像編集</h4>
        <div class="back_btn">
          <i class="fas fa-angle-left fa-lg"></i><%= link_to "戻る", menu_menu_images_path(@menu), class: "font-20" %>
        </div>
        <hr>
        <%= form_for @menu_image, url: menu_menu_image_path(@menu, @menu_image), method: :patch do |f|  %>
          <%= render partial: "menu_images/form", locals:{f:f, menu_image: @menu_image, img: @menu_image.file_name.url, btn: "編集"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/menu_images/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="content_box">
        <h4 class="center">『<%= @menu.name %>』<br>画像一覧</h4>
        <div class="back_btn">
          <i class="fas fa-angle-left fa-lg"></i><%= link_to "戻る", shops_menu_path(@menu), class: "font-20" %>
        </div>
        <hr>
        <% if @menu_images.present? %>
          <% 4.times do |i| %>
            <div class="content_box_detail ribon">
              <% if @menu_images[i].present? %>
                <%= image_tag @menu_images[i].file_name.thumb_width.to_s %>
                <% if @menu_images[i].is_main? %>
                  <div class="caption"><span>メイン</span></div>
                <% end %>
                <div class="edit_btn ma-t-50">
                  <%= link_to "この画像を編集する", edit_menu_menu_image_path(@menu, @menu_images[i]), class: "btn btn-primary btn-sm" %>
                  <% unless @menu_images[i] == @main_image %>
                    <%= link_to "この画像を削除する", menu_menu_image_path(@menu, @menu_images[i]), method: :delete, class: "btn btn-danger btn-sm" %>
                  <% end %>
                </div>
              <% else %>
                <%= image_tag "noimage.png", class:"wid-100" %>
                <div class="add_btn ma-t-50">
                  <%= link_to "画像を追加する", new_menu_menu_image_path(@menu), class: "btn btn-primary btn-sm" %>
                </div>
              <% end %>
            </div>
            <hr>
          <% end %>
        <% else %>
          <% 4.times do |i| %>
            <div class="content_box_detail">
              <%= image_tag "noimage.png", class:"wid-100" %>
              <div class="add_btn ma-t-50">
                <%= link_to "画像を追加する", new_menu_menu_image_path(@menu), class: "btn btn-primary btn-sm" %>
              </div>
            </div>
            <hr>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/menu_images/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="form_box">
        <h4 class="center">『<%= @menu.name %>』<br>画像追加</h4>
        <div class="back_btn">
          <i class="fas fa-angle-left fa-lg"></i><%= link_to "戻る", menu_menu_images_path(@menu), class: "font-20" %>
        </div>
        <hr>
        <%= form_for @menu_image, url: menu_menu_images_path(@menu) do |f|  %>
          <%= render partial: "menu_images/form", locals:{f:f, menu_image: @menu_image, img: "noimage.png", btn: "追加する"} %>
        <% end %>

      </div>
    </div>
  </div>
</div>
<script>
  $(function() {
    // disable auto discover
    Dropzone.autoDiscover = false;

    $(".dropzone").dropzone({
      maxFilesize: 1,
      addRemoveLinks: true
    });
  });
</script>